name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 16 * * 1-5'  # Runs at 16:00 UTC (market close) on weekdays
  workflow_dispatch:  # Allows manual triggers

permissions:
  contents: write  # This gives the workflow permission to write to the repository

jobs:
  analyze_stocks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic GITHUB_TOKEN
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run stock analysis
      run: python main.py
      
    - name: Commit and push results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results_*.csv
        git commit -m "Add stock analysis results for $(date +'%Y-%m-%d')" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
